/**
 * OKLCH-native CSS generator.
 *
 * Takes an AutomakerThemeConfig and produces a complete CSS rule
 * with all 102 custom properties. Drop-in replacement for hand-written theme files.
 */

import type { AutomakerThemeConfig } from '../config/theme-config';
import { parseOklch, oklchString } from '../config/color-scales';

/**
 * Derive a color with reduced chroma (for hover states, etc).
 */
function withAlpha(baseColor: string, alpha: number): string {
  const parsed = parseOklch(baseColor);
  if (!parsed) return baseColor;
  return oklchString(parsed.l, parsed.c, parsed.h, alpha);
}

/**
 * Generate complete CSS for a theme config.
 *
 * Output format: `:root.{name} { --background: oklch(...); ... }`
 * Matches the format of existing hand-written theme files.
 */
export function generateThemeCSS(config: AutomakerThemeConfig): string {
  const { name, isDark, colors, status, surfaces, foreground, borders, brand } = config;

  // Derive brand colors from primary scale if not explicitly set
  const brandColors = brand ?? {
    400: colors.primary[400],
    500: colors.primary[500],
    600: colors.primary[600],
  };

  // Derive action colors from primary
  const actionView = colors.primary[isDark ? 400 : 500];
  const actionViewHover = colors.primary[isDark ? 500 : 600];
  const actionFollowup = oklchString(isDark ? 0.6 : 0.55, 0.16, 230);
  const actionFollowupHover = oklchString(isDark ? 0.55 : 0.5, 0.18, 230);
  const actionCommit = oklchString(isDark ? 0.6 : 0.55, 0.15, 145);
  const actionCommitHover = oklchString(isDark ? 0.55 : 0.5, 0.17, 145);

  // Derive running indicator from primary
  const runningIndicator = colors.primary[isDark ? 400 : 500];
  const runningIndicatorText = colors.primary[isDark ? 300 : 600];

  // Derive status backgrounds
  const statusSuccessBg = withAlpha(status.success, isDark ? 0.2 : 0.15);
  const statusWarningBg = withAlpha(status.warning, isDark ? 0.2 : 0.15);
  const statusErrorBg = withAlpha(status.error, isDark ? 0.2 : 0.15);
  const statusInfoBg = withAlpha(status.info, isDark ? 0.2 : 0.15);

  // Derive workflow status colors
  const statusBacklog = oklchString(isDark ? 0.55 : 0.5, 0.0, 0);
  const statusInProgress = status.warning;
  const statusWaiting = oklchString(isDark ? 0.7 : 0.65, 0.14, 50);
  const statusReview = status.info;
  const statusBlocked = status.error;
  const statusDone = status.success;

  // Derive shadows
  const shadowAlpha = isDark
    ? [0.3, 0.4, 0.3, 0.4, 0.3, 0.4, 0.2, 0.5, 0.3]
    : [0.05, 0.1, 0.06, 0.1, 0.06, 0.1, 0.05, 0.1, 0.04];

  // Derive sidebar tokens from surfaces + primary
  const sidebarFg = foreground.default;
  const sidebarPrimary = brandColors[500];
  const sidebarPrimaryFg = foreground.default;
  const sidebarAccent = isDark ? oklchString(0.93, 0, 0, 0.05) : surfaces.muted;
  const sidebarAccentFg = foreground.default;
  const sidebarBorder = isDark ? oklchString(0.93, 0, 0, 0.08) : borders.default;
  const sidebarRing = borders.ring;

  // Chart colors — spread across primary + status hues
  const chart1 = brandColors[500];
  const chart2 = status.success;
  const chart3 = status.warning;
  const chart4 = status.info;
  const chart5 = status.error;

  // Radius
  const radius = config.radius ?? '0.5rem';

  const lines = [
    `/* ${config.displayName} Theme — Generated by protoMaker */`,
    ``,
    `:root.${name} {`,
    `  /* Surfaces */`,
    `  --background: ${surfaces.background};`,
    `  --background-50: ${withAlpha(surfaces.background, 0.5)};`,
    `  --background-80: ${withAlpha(surfaces.background, 0.8)};`,
    `  --card: ${surfaces.card};`,
    `  --card-foreground: ${foreground.default};`,
    `  --popover: ${surfaces.popover};`,
    `  --popover-foreground: ${foreground.default};`,
    `  --secondary: ${surfaces.secondary};`,
    `  --secondary-foreground: ${foreground.default};`,
    `  --muted: ${surfaces.muted};`,
    `  --muted-foreground: ${foreground.muted};`,
    `  --accent: ${isDark ? oklchString(0.93, 0, 0, 0.06) : surfaces.muted};`,
    `  --accent-foreground: ${foreground.default};`,
    `  --input: ${surfaces.input};`,
    ``,
    `  /* Text hierarchy */`,
    `  --foreground: ${foreground.default};`,
    `  --foreground-secondary: ${foreground.secondary};`,
    `  --foreground-muted: ${foreground.muted};`,
    ``,
    `  /* Brand / Primary */`,
    `  --primary: ${brandColors[500]};`,
    `  --primary-foreground: ${isDark ? foreground.default : oklchString(1, 0, 0)};`,
    `  --brand-400: ${brandColors[400]};`,
    `  --brand-500: ${brandColors[500]};`,
    `  --brand-600: ${brandColors[600]};`,
    ``,
    `  /* Borders */`,
    `  --border: ${borders.default};`,
    `  --border-glass: ${borders.glass};`,
    `  --ring: ${borders.ring};`,
    `  --destructive: ${status.error};`,
    ``,
    `  /* Radius */`,
    `  --radius: ${radius};`,
    ``,
    `  /* Sidebar */`,
    `  --sidebar: ${surfaces.sidebar};`,
    `  --sidebar-foreground: ${sidebarFg};`,
    `  --sidebar-primary: ${sidebarPrimary};`,
    `  --sidebar-primary-foreground: ${sidebarPrimaryFg};`,
    `  --sidebar-accent: ${sidebarAccent};`,
    `  --sidebar-accent-foreground: ${sidebarAccentFg};`,
    `  --sidebar-border: ${sidebarBorder};`,
    `  --sidebar-ring: ${sidebarRing};`,
    ``,
    `  /* Chart colors */`,
    `  --chart-1: ${chart1};`,
    `  --chart-2: ${chart2};`,
    `  --chart-3: ${chart3};`,
    `  --chart-4: ${chart4};`,
    `  --chart-5: ${chart5};`,
    ``,
    `  /* Action buttons */`,
    `  --action-view: ${actionView};`,
    `  --action-view-hover: ${actionViewHover};`,
    `  --action-followup: ${actionFollowup};`,
    `  --action-followup-hover: ${actionFollowupHover};`,
    `  --action-commit: ${actionCommit};`,
    `  --action-commit-hover: ${actionCommitHover};`,
    `  --action-verify: ${actionCommit};`,
    `  --action-verify-hover: ${actionCommitHover};`,
    ``,
    `  /* Running indicator */`,
    `  --running-indicator: ${runningIndicator};`,
    `  --running-indicator-text: ${runningIndicatorText};`,
    ``,
    `  /* Status colors */`,
    `  --status-success: ${status.success};`,
    `  --status-success-bg: ${statusSuccessBg};`,
    `  --status-warning: ${status.warning};`,
    `  --status-warning-bg: ${statusWarningBg};`,
    `  --status-error: ${status.error};`,
    `  --status-error-bg: ${statusErrorBg};`,
    `  --status-info: ${status.info};`,
    `  --status-info-bg: ${statusInfoBg};`,
    `  --status-backlog: ${statusBacklog};`,
    `  --status-in-progress: ${statusInProgress};`,
    `  --status-waiting: ${statusWaiting};`,
    `  --status-review: ${statusReview};`,
    `  --status-blocked: ${statusBlocked};`,
    `  --status-done: ${statusDone};`,
    ``,
    `  /* Shadows */`,
    `  --shadow-xs: 0 1px 2px rgba(0, 0, 0, ${shadowAlpha[0]});`,
    `  --shadow-sm: 0 1px 3px rgba(0, 0, 0, ${shadowAlpha[1]}), 0 1px 2px rgba(0, 0, 0, ${shadowAlpha[2]});`,
    `  --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, ${shadowAlpha[3]}), 0 2px 4px -1px rgba(0, 0, 0, ${shadowAlpha[4]});`,
    `  --shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, ${shadowAlpha[5]}), 0 4px 6px -2px rgba(0, 0, 0, ${shadowAlpha[6]});`,
    `  --shadow-xl: 0 20px 25px -5px rgba(0, 0, 0, ${shadowAlpha[7]}), 0 10px 10px -5px rgba(0, 0, 0, ${shadowAlpha[8]});`,
    `}`,
    ``,
    `/* Theme-specific overrides */`,
    ``,
    `.${name} .animated-outline-gradient {`,
    `  background: conic-gradient(from 90deg at 50% 50%, ${brandColors[400]} 0%, ${brandColors[600]} 50%, ${brandColors[400]} 100%);`,
    `}`,
    ``,
    `.${name} .animated-outline-inner {`,
    `  background: ${surfaces.card} !important;`,
    `  color: ${brandColors[400]} !important;`,
    `}`,
    ``,
    `.${name} [data-slot='button'][class*='animated-outline']:hover .animated-outline-inner {`,
    `  background: ${surfaces.muted} !important;`,
    `  color: ${brandColors[500]} !important;`,
    `}`,
    ``,
    `.${name} .slider-track {`,
    `  background: ${surfaces.muted};`,
    `}`,
    ``,
    `.${name} .slider-range {`,
    `  background: linear-gradient(to right, ${brandColors[400]}, ${brandColors[600]});`,
    `}`,
    ``,
    `.${name} .slider-thumb {`,
    `  background: ${surfaces.card};`,
    `  border-color: ${borders.default};`,
    `}`,
    ``,
    `.${name} .content-bg {`,
    `  background: ${surfaces.background};`,
    `}`,
  ];

  return lines.join('\n');
}
