/**
 * html-generator.ts
 *
 * Generates semantic HTML5 files from PenDocument / PenFrame nodes.
 *
 *  - One standalone .html file per reusable frame.
 *  - Semantic element selection based on node type + name heuristics.
 *  - CSS custom properties referenced via var() in inline style attributes.
 *  - Links to the companion .css file generated by css-generator.ts.
 *
 * Usage:
 * ```ts
 * import { generateHTMLFromDocument } from './html-generator.js';
 *
 * const files = generateHTMLFromDocument(myPenDocument);
 * for (const file of files) {
 *   fs.writeFileSync(file.filename, file.content, 'utf-8');
 * }
 * ```
 */

import { toCSSClassName } from './css-generator.js';

// ============================================================================
// Minimal local types (structural match to pen.ts PenNode family)
// ============================================================================

interface LocalFill {
  type: 'solid' | 'gradient' | 'image';
  color?: string;
  opacity?: number;
  gradientType?: 'linear' | 'radial';
  stops?: Array<{ position: number; color: string }>;
  imageRef?: string;
}

interface LocalStroke {
  color: string;
  width: number;
  opacity?: number;
}

interface LocalNodeBase {
  id: string;
  name?: string;
  visible?: boolean;
  opacity?: number;
  reusable?: boolean;
}

interface LocalFrame extends LocalNodeBase {
  type: 'frame';
  children: LocalNode[];
  fills?: LocalFill[];
  strokes?: LocalStroke[];
  cornerRadius?: number;
  layoutMode?: 'none' | 'horizontal' | 'vertical';
  paddingLeft?: number;
  paddingRight?: number;
  paddingTop?: number;
  paddingBottom?: number;
  itemSpacing?: number;
  clipsContent?: boolean;
}

interface LocalGroup extends LocalNodeBase {
  type: 'group';
  children: LocalNode[];
}

interface LocalText extends LocalNodeBase {
  type: 'text';
  content: string;
  fontSize: number;
  fontFamily: string;
  fontWeight?: number | string;
  textAlign?: 'left' | 'center' | 'right' | 'justify';
  fills?: LocalFill[];
}

interface LocalIconFont extends LocalNodeBase {
  type: 'icon-font';
  character: string;
  fontFamily: string;
  fontSize: number;
  fills?: LocalFill[];
}

interface LocalRectangle extends LocalNodeBase {
  type: 'rectangle';
  width: number;
  height: number;
  fills?: LocalFill[];
  strokes?: LocalStroke[];
  cornerRadius?: number;
}

interface LocalEllipse extends LocalNodeBase {
  type: 'ellipse';
  width: number;
  height: number;
  fills?: LocalFill[];
  strokes?: LocalStroke[];
}

interface LocalRef extends LocalNodeBase {
  type: 'ref';
  refId: string;
}

interface LocalPath extends LocalNodeBase {
  type: 'path';
  pathData: string;
  fills?: LocalFill[];
  strokes?: LocalStroke[];
}

type LocalNode =
  | LocalFrame
  | LocalGroup
  | LocalText
  | LocalIconFont
  | LocalRectangle
  | LocalEllipse
  | LocalRef
  | LocalPath;

interface LocalDocument {
  variables?: Array<{ id: string; name: string; type: string; values: Record<string, unknown> }>;
  children: LocalNode[];
}

// ============================================================================
// Generator Output
// ============================================================================

/** A single generated HTML file. */
export interface GeneratedHTMLFile {
  /** Filename, e.g. 'my-button.html'. */
  filename: string;
  /** kebab-case component name, e.g. 'my-button'. */
  componentName: string;
  /** Complete HTML5 source code ready to write to disk. */
  content: string;
}

// ============================================================================
// Semantic Element Selection
// ============================================================================

const SEMANTIC_NAME_MAP: Record<string, string> = {
  button: 'button',
  btn: 'button',
  nav: 'nav',
  navigation: 'nav',
  header: 'header',
  footer: 'footer',
  main: 'main',
  aside: 'aside',
  article: 'article',
  section: 'section',
  form: 'form',
  label: 'label',
  list: 'ul',
  'list-item': 'li',
  item: 'li',
  card: 'article',
  dialog: 'dialog',
  modal: 'dialog',
  hero: 'section',
  banner: 'section',
};

/**
 * Pick an appropriate HTML5 semantic element based on node type and name.
 * Falls back to 'div' for containers and 'span' for text with unknown names.
 *
 * @param type  The PenNode type string.
 * @param name  The optional design name of the node.
 */
export function pickSemanticElement(type: string, name: string | undefined): string {
  if (type === 'text') {
    const n = (name ?? '').toLowerCase();
    if (n.startsWith('h1')) return 'h1';
    if (n.startsWith('h2')) return 'h2';
    if (n.startsWith('h3')) return 'h3';
    if (n.startsWith('h4')) return 'h4';
    if (n.startsWith('h5')) return 'h5';
    if (n.startsWith('h6')) return 'h6';
    if (n === 'label' || n.includes('label')) return 'label';
    if (n === 'p' || n.includes('paragraph') || n.includes('body')) return 'p';
    return 'span';
  }

  const nameLower = (name ?? '').toLowerCase().trim();
  for (const [key, element] of Object.entries(SEMANTIC_NAME_MAP)) {
    if (nameLower === key || nameLower.startsWith(`${key}-`) || nameLower.endsWith(`-${key}`)) {
      return element;
    }
  }

  return 'div';
}

// ============================================================================
// Utilities
// ============================================================================

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function resolveColor(color: string): string {
  return color.startsWith('$') ? `var(${color.slice(1)})` : color;
}

// ============================================================================
// Inline Style Building
// ============================================================================

function buildFrameStyle(node: LocalFrame): Record<string, string> {
  const s: Record<string, string> = {};

  const fill = (node.fills ?? [])[0];
  if (fill?.type === 'solid' && fill.color) {
    s['background'] = resolveColor(fill.color);
  } else if (fill?.type === 'gradient' && fill.stops && fill.stops.length > 0) {
    const stopList = fill.stops
      .map((st) => `${resolveColor(st.color)} ${Math.round(st.position * 100)}%`)
      .join(', ');
    const fn = fill.gradientType === 'radial' ? 'radial-gradient' : 'linear-gradient';
    const dir = fill.gradientType === 'radial' ? 'circle' : 'to bottom';
    s['background'] = `${fn}(${dir}, ${stopList})`;
  }

  const stroke = (node.strokes ?? [])[0];
  if (stroke) {
    s['border'] = `${stroke.width}px solid ${resolveColor(stroke.color)}`;
  }

  if (node.cornerRadius !== undefined && node.cornerRadius > 0) {
    s['border-radius'] = `${node.cornerRadius}px`;
  }
  if (node.opacity !== undefined && node.opacity < 1) {
    s['opacity'] = String(node.opacity);
  }
  if (node.clipsContent) {
    s['overflow'] = 'hidden';
  }
  if (node.layoutMode && node.layoutMode !== 'none') {
    s['display'] = 'flex';
    s['flex-direction'] = node.layoutMode === 'horizontal' ? 'row' : 'column';
    if (node.itemSpacing && node.itemSpacing > 0) {
      s['gap'] = `${node.itemSpacing}px`;
    }
  }

  const hasPadding = node.paddingTop || node.paddingRight || node.paddingBottom || node.paddingLeft;
  if (hasPadding) {
    const t = node.paddingTop ?? 0;
    const r = node.paddingRight ?? 0;
    const b = node.paddingBottom ?? 0;
    const l = node.paddingLeft ?? 0;
    s['padding'] = `${t}px ${r}px ${b}px ${l}px`;
  }

  return s;
}

function styleString(styles: Record<string, string>): string {
  const entries = Object.entries(styles);
  if (entries.length === 0) return '';
  return entries.map(([k, v]) => `${k}: ${v}`).join('; ');
}

// ============================================================================
// Per-type Node Serializers
// ============================================================================

function serializeTextNode(node: LocalText, className: string, depth: number): string {
  const ind = '  '.repeat(depth);
  const tag = pickSemanticElement('text', node.name);
  const styles: Record<string, string> = {};

  if (node.fontSize) styles['font-size'] = `${node.fontSize}px`;
  if (node.fontFamily) styles['font-family'] = node.fontFamily;
  if (node.fontWeight !== undefined) styles['font-weight'] = String(node.fontWeight);
  if (node.textAlign) styles['text-align'] = node.textAlign;
  if (node.opacity !== undefined && node.opacity < 1) {
    styles['opacity'] = String(node.opacity);
  }

  const fill = (node.fills ?? [])[0];
  if (fill?.type === 'solid' && fill.color) {
    styles['color'] = resolveColor(fill.color);
  }

  const styleAttr = styleString(styles);
  const style = styleAttr ? ` style="${styleAttr}"` : '';
  const content = escapeHtml(node.content ?? '');
  return `${ind}<${tag} class="${className}"${style}>${content}</${tag}>`;
}

function serializeIconFontNode(node: LocalIconFont, className: string, depth: number): string {
  const ind = '  '.repeat(depth);
  const styles: Record<string, string> = {
    'font-size': `${node.fontSize}px`,
    'font-family': node.fontFamily,
  };

  const fill = (node.fills ?? [])[0];
  if (fill?.type === 'solid' && fill.color) {
    styles['color'] = resolveColor(fill.color);
  }

  const style = styleString(styles);
  return `${ind}<span class="${className}" style="${style}" aria-hidden="true">${escapeHtml(node.character)}</span>`;
}

function serializeRectangleNode(node: LocalRectangle, className: string, depth: number): string {
  const ind = '  '.repeat(depth);
  const styles: Record<string, string> = {};

  const fill = (node.fills ?? [])[0];
  if (fill?.type === 'solid' && fill.color) styles['background'] = resolveColor(fill.color);

  const stroke = (node.strokes ?? [])[0];
  if (stroke) styles['border'] = `${stroke.width}px solid ${resolveColor(stroke.color)}`;

  if (node.cornerRadius !== undefined && node.cornerRadius > 0) {
    styles['border-radius'] = `${node.cornerRadius}px`;
  }
  if (node.opacity !== undefined && node.opacity < 1) styles['opacity'] = String(node.opacity);
  if (node.width) styles['width'] = `${node.width}px`;
  if (node.height) styles['height'] = `${node.height}px`;

  const style = styleString(styles);
  const styleAttr = style ? ` style="${style}"` : '';
  return `${ind}<div role="presentation" class="${className}"${styleAttr}></div>`;
}

function serializeEllipseNode(node: LocalEllipse, className: string, depth: number): string {
  const ind = '  '.repeat(depth);
  const styles: Record<string, string> = { 'border-radius': '50%' };

  const fill = (node.fills ?? [])[0];
  if (fill?.type === 'solid' && fill.color) styles['background'] = resolveColor(fill.color);

  const stroke = (node.strokes ?? [])[0];
  if (stroke) styles['border'] = `${stroke.width}px solid ${resolveColor(stroke.color)}`;

  if (node.opacity !== undefined && node.opacity < 1) styles['opacity'] = String(node.opacity);
  if (node.width) styles['width'] = `${node.width}px`;
  if (node.height) styles['height'] = `${node.height}px`;

  const style = styleString(styles);
  return `${ind}<div role="presentation" class="${className}" style="${style}"></div>`;
}

function serializePathNode(node: LocalPath, className: string, depth: number): string {
  const ind = '  '.repeat(depth);
  const ind2 = '  '.repeat(depth + 1);
  const fill = (node.fills ?? [])[0];
  const fillColor =
    fill?.type === 'solid' && fill.color ? resolveColor(fill.color) : 'currentColor';
  // Pen parser uses `path`, codegen uses `pathData` — accept both
  const pathData = node.pathData ?? (node as unknown as { path?: string }).path ?? '';
  return [
    `${ind}<svg class="${className}" aria-hidden="true">`,
    `${ind2}<path d="${escapeHtml(pathData)}" fill="${fillColor}" />`,
    `${ind}</svg>`,
  ].join('\n');
}

function serializeFrameNode(node: LocalFrame, className: string, depth: number): string {
  const ind = '  '.repeat(depth);
  const tag = pickSemanticElement('frame', node.name);
  const styles = buildFrameStyle(node);
  const style = styleString(styles);
  const styleAttr = style ? ` style="${style}"` : '';
  const ariaLabel = node.name ? ` aria-label="${escapeHtml(node.name)}"` : '';

  const children = (node.children ?? [])
    .map((child) => serializeNode(child, className, depth + 1))
    .filter(Boolean)
    .join('\n');

  if (!children) {
    return `${ind}<${tag} class="${className}"${styleAttr}${ariaLabel}></${tag}>`;
  }

  return [
    `${ind}<${tag} class="${className}"${styleAttr}${ariaLabel}>`,
    children,
    `${ind}</${tag}>`,
  ].join('\n');
}

function serializeGroupNode(node: LocalGroup, className: string, depth: number): string {
  const ind = '  '.repeat(depth);
  const children = (node.children ?? [])
    .map((child) => serializeNode(child, className, depth + 1))
    .filter(Boolean)
    .join('\n');

  if (!children) {
    return `${ind}<div class="${className}"></div>`;
  }

  return [`${ind}<div class="${className}">`, children, `${ind}</div>`].join('\n');
}

// ============================================================================
// Main Dispatch
// ============================================================================

function serializeNode(node: LocalNode, parentClass: string, depth: number): string {
  if (node.visible === false) return '';

  const childName = toCSSClassName(node.name ?? node.id);
  const className = `${parentClass}__${childName}`;

  switch (node.type) {
    case 'ref':
      return `${'  '.repeat(depth)}<!-- ref: ${escapeHtml(node.refId)} — resolve manually -->`;
    case 'path':
      return serializePathNode(node, className, depth);
    case 'text':
      return serializeTextNode(node, className, depth);
    case 'icon-font':
      return serializeIconFontNode(node, className, depth);
    case 'rectangle':
      return serializeRectangleNode(node, className, depth);
    case 'ellipse':
      return serializeEllipseNode(node, className, depth);
    case 'frame':
      return serializeFrameNode(node, className, depth);
    case 'group':
      return serializeGroupNode(node, className, depth);
  }
}

// ============================================================================
// Frame HTML Generator
// ============================================================================

/**
 * Generate a complete standalone HTML5 file for a single reusable PenFrame.
 *
 * The file includes:
 *  - Proper DOCTYPE + head with charset + viewport meta
 *  - A `<link>` to the companion .css file
 *  - A root element using BEM root class (e.g. `.my-button`)
 *  - Semantic child elements with BEM modifier classes
 *
 * @param frame  The frame node (must have `reusable: true`).
 * @param _doc   The parent PenDocument (reserved for future metadata use).
 */
export function generateHTMLFromFrame(frame: LocalFrame, _doc: LocalDocument): GeneratedHTMLFile {
  const componentName = toCSSClassName(frame.name ?? frame.id);
  const filename = `${componentName}.html`;

  const rootStyles = buildFrameStyle(frame);
  const rootStyle = styleString(rootStyles);
  const styleAttr = rootStyle ? ` style="${rootStyle}"` : '';
  const ariaLabel = frame.name ? ` aria-label="${escapeHtml(frame.name)}"` : '';

  const childrenHTML = (frame.children ?? [])
    .map((child) => serializeNode(child, componentName, 2))
    .filter(Boolean)
    .join('\n');

  const title = escapeHtml(frame.name ?? componentName);
  const rootTag = pickSemanticElement('frame', frame.name);

  const lines: string[] = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="UTF-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    `  <title>${title}</title>`,
    `  <link rel="stylesheet" href="./${componentName}.css" />`,
    '</head>',
    '<body>',
    `  <${rootTag} class="${componentName}"${styleAttr}${ariaLabel}>`,
  ];

  if (childrenHTML) {
    lines.push(childrenHTML);
  }

  lines.push(`  </${rootTag}>`, '</body>', '</html>', '');

  return { filename, componentName, content: lines.join('\n') };
}

// ============================================================================
// Document-Level HTML Generator
// ============================================================================

/**
 * Generate HTML files for every reusable component in a PenDocument.
 *
 * @param doc     The parsed PenDocument.
 * @returns       Array of generated files (one per reusable component).
 *
 * @example
 * ```ts
 * import { generateHTMLFromDocument } from '@design-system/codegen/html-generator';
 *
 * const files = generateHTMLFromDocument(doc);
 * for (const { filename, content } of files) {
 *   fs.writeFileSync(`dist/${filename}`, content);
 * }
 * ```
 */
export function generateHTMLFromDocument(doc: LocalDocument): GeneratedHTMLFile[] {
  const components: LocalFrame[] = [];

  function walk(nodes: LocalNode[]): void {
    for (const node of nodes) {
      if (node.type === 'frame' && node.reusable) {
        components.push(node);
        // Don't recurse — nested reusable frames become separate components.
        continue;
      }
      if (node.type === 'frame' || node.type === 'group') {
        walk(node.children ?? []);
      }
    }
  }

  walk(doc.children);
  return components.map((frame) => generateHTMLFromFrame(frame, doc));
}
