/**
 * proto-config-writer
 *
 * Generates proto.config.yaml from a repo research result and writes it
 * to the project root. No server or API key required.
 */

import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import { stringify as yamlStringify } from 'yaml';
import type { RepoResearchResult } from 'create-protolab';

export interface ProtoConfig {
  name: string;
  version: string;
  protolab: {
    enabled: boolean;
  };
  techStack: {
    language: string;
    framework?: string;
    packageManager: string;
  };
  commands: {
    build?: string;
    test?: string;
    format?: string;
    lint?: string;
    dev?: string;
  };
  standard?: {
    skip?: string[];
  };
  settings: Record<string, unknown>;
}

/** Derive the primary language from research results */
function detectLanguage(research: RepoResearchResult): string {
  if (research.python.hasPythonServices) return 'python';
  if (research.codeQuality.hasTypeScript) return 'typescript';
  return 'javascript';
}

/** Derive the primary framework from research results */
function detectFramework(research: RepoResearchResult): string | undefined {
  if (research.frontend.metaFramework && research.frontend.metaFramework !== 'none') {
    return research.frontend.metaFramework;
  }
  if (research.frontend.framework && research.frontend.framework !== 'none') {
    return research.frontend.framework;
  }
  if (research.backend.hasPayload) return 'payload';
  if (research.backend.hasExpress) return 'express';
  return undefined;
}

/** Infer common build/test/dev commands from research */
function inferCommands(research: RepoResearchResult): ProtoConfig['commands'] {
  const pm =
    research.monorepo.packageManager === 'unknown' ? 'npm' : research.monorepo.packageManager;
  const run = pm === 'npm' ? 'npm run' : pm === 'yarn' ? 'yarn' : `${pm} run`;
  return {
    build: `${run} build`,
    test: `${run} test`,
    format: `${run} format`,
    lint: `${run} lint`,
    dev: `${run} dev`,
  };
}

/** Build a ProtoConfig object from research results */
export function buildProtoConfig(research: RepoResearchResult): ProtoConfig {
  const pm =
    research.monorepo.packageManager === 'unknown' ? 'npm' : research.monorepo.packageManager;
  const framework = detectFramework(research);

  const config: ProtoConfig = {
    name: research.projectName,
    version: '0.1.0',
    protolab: {
      enabled: true,
    },
    techStack: {
      language: detectLanguage(research),
      ...(framework ? { framework } : {}),
      packageManager: pm,
    },
    commands: inferCommands(research),
    settings: {},
  };

  // Add monorepo info if applicable
  if (research.monorepo.isMonorepo) {
    config.settings['monorepo'] = {
      tool: research.monorepo.tool,
      packages: research.monorepo.packages.map((p) => p.path),
    };
  }

  return config;
}

/** Write proto.config.yaml to the project root. Skips if already exists. */
export async function writeProtoConfig(
  projectPath: string,
  research: RepoResearchResult
): Promise<{ filePath: string; skipped: boolean }> {
  const configPath = path.join(projectPath, 'proto.config.yaml');

  // Check if file already exists
  try {
    await fs.access(configPath);
    return { filePath: configPath, skipped: true };
  } catch {
    // File doesn't exist — proceed
  }

  const config = buildProtoConfig(research);
  const yamlContent =
    `# proto.config.yaml — ProtoLabs project configuration\n` +
    `# Generated by @protolabsai/setup on ${new Date().toISOString()}\n` +
    `# Documentation: https://protolabs.studio/docs/config\n\n` +
    yamlStringify(config, { lineWidth: 120 });

  await fs.writeFile(configPath, yamlContent, 'utf-8');
  return { filePath: configPath, skipped: false };
}
