/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router.
// You should NOT make changes to this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createRouter } from '@tanstack/react-router';

import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as SessionsRoute } from './routes/sessions';
import { Route as SettingsRoute } from './routes/settings';
import { Route as FlowsRoute } from './routes/flows';
import { Route as PromptsRoute } from './routes/prompts';

// Build the route tree
export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SessionsRoute,
  SettingsRoute,
  FlowsRoute,
  PromptsRoute,
]);

// Create and export the router instance
export const router = createRouter({ routeTree });

// Register the router with TanStack Router's type system
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
