/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router.
// You should NOT make changes to this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// ──────────────────────────────────────────────────────────────────────────────
// This is a minimal stub. Run `npm run dev` to regenerate with full type info.
// ──────────────────────────────────────────────────────────────────────────────

import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as SessionsRoute } from './routes/sessions';
import { Route as SettingsRoute } from './routes/settings';

// Build the route tree
export const routeTree = rootRoute.addChildren([IndexRoute, SessionsRoute, SettingsRoute]);
