/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router.
// You should NOT make changes to this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// ──────────────────────────────────────────────────────────────────────────────
// This is a minimal stub. Run `npm run dev` to regenerate with full type info.
// ──────────────────────────────────────────────────────────────────────────────

import { createRoute } from '@tanstack/react-router';
import { Route as rootRoute } from './routes/__root';

// Import components from route files
import { Route as IndexFileRoute } from './routes/index';
import { Route as SessionsFileRoute } from './routes/sessions';
import { Route as SettingsFileRoute } from './routes/settings';
import { Route as FlowsFileRoute } from './routes/flows';
import { Route as PromptsFileRoute } from './routes/prompts';

// Re-create routes with proper parent wiring and explicit paths
const IndexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: IndexFileRoute.options?.component,
});

const SessionsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/sessions',
  component: SessionsFileRoute.options?.component,
});

const SettingsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/settings',
  component: SettingsFileRoute.options?.component,
});

const FlowsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/flows',
  component: FlowsFileRoute.options?.component,
});

const PromptsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/prompts',
  component: PromptsFileRoute.options?.component,
});

// Build the route tree
export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SessionsRoute,
  SettingsRoute,
  FlowsRoute,
  PromptsRoute,
]);
