/**
 * Event types for AutoMaker event system
 */

export type EventType =
  | 'agent:stream'
  | 'auto-mode:event'
  | 'auto-mode:started'
  | 'auto-mode:stopped'
  | 'auto-mode:idle'
  | 'auto-mode:error'
  | 'auto-mode:health-check'
  | 'backlog-plan:event'
  | 'feature:created'
  | 'feature:started'
  | 'feature:completed'
  | 'feature:stopped'
  | 'feature:error'
  | 'feature:progress'
  | 'feature:tool-use'
  | 'feature:follow-up-started'
  | 'feature:follow-up-completed'
  | 'feature:verified'
  | 'feature:committed'
  | 'feature:retry'
  | 'feature:recovery'
  | 'feature:pr-merged'
  | 'project:analysis-started'
  | 'project:analysis-progress'
  | 'project:analysis-completed'
  | 'project:analysis-error'
  | 'project:features:start'
  | 'project:features:progress'
  | 'project:features:error'
  | 'project:features:done'
  | 'suggestions:event'
  | 'spec-regeneration:event'
  | 'issue-validation:event'
  | 'ideation:stream'
  | 'ideation:session-started'
  | 'ideation:session-ended'
  | 'ideation:analysis'
  | 'ideation:analysis-started'
  | 'ideation:analysis-progress'
  | 'ideation:analysis-complete'
  | 'ideation:analysis-error'
  | 'ideation:suggestions'
  | 'ideation:idea-created'
  | 'ideation:idea-updated'
  | 'ideation:idea-deleted'
  | 'ideation:idea-converted'
  | 'worktree:init-started'
  | 'worktree:init-output'
  | 'worktree:init-completed'
  | 'dev-server:started'
  | 'dev-server:output'
  | 'dev-server:stopped'
  | 'skill:created'
  | 'memory:learning'
  | 'notification:created'
  | 'health:check-completed'
  | 'health:issue-detected'
  | 'health:issue-remediated'
  | 'scheduler:started'
  | 'scheduler:stopped'
  | 'scheduler:task_registered'
  | 'scheduler:task_unregistered'
  | 'scheduler:task_enabled'
  | 'scheduler:task_disabled'
  | 'scheduler:task_started'
  | 'scheduler:task_completed'
  | 'recovery_analysis'
  | 'recovery_started'
  | 'recovery_completed'
  | 'recovery_recorded'
  | 'recovery_escalated'
  // Ralph mode events (persistent retry loops)
  | 'ralph:started'
  | 'ralph:iteration_started'
  | 'ralph:iteration_completed'
  | 'ralph:verification_started'
  | 'ralph:verification_completed'
  | 'ralph:verified'
  | 'ralph:paused'
  | 'ralph:resumed'
  | 'ralph:stopped'
  | 'ralph:max_iterations'
  | 'ralph:error'
  | 'ralph:progress'
  // Headsdown agent events (autonomous agents)
  | 'headsdown:agent:started'
  | 'headsdown:agent:stopped'
  | 'headsdown:agent:working'
  | 'headsdown:agent:idle'
  | 'headsdown:agent:error'
  | 'headsdown:agent:paused'
  | 'headsdown:agent:resumed'
  // GOAP brain loop events
  | 'goap:started'
  | 'goap:stopped'
  | 'goap:paused'
  | 'goap:resumed'
  | 'goap:tick'
  | 'goap:world_state_updated'
  | 'goap:action_selected'
  | 'goap:action_executed'
  | 'goap:action_failed'
  | 'goap:no_action_available'
  | 'goap:error'
  | 'goap:plan_generated'
  | 'goap:plan_invalidated'
  | 'goap:plan_step_executed'
  | 'goap:plan_completed'
  // CodeRabbit review events
  | 'coderabbit:review-received'
  | 'coderabbit:feedback-processed'
  | 'coderabbit:link-created'
  // Webhook events
  | 'webhook:github:issue'
  | 'webhook:github:pull_request'
  | 'webhook:github:push'
  // Integration events
  | 'integration:linear'
  | 'integration:discord'
  // Project orchestration events
  | 'project:scaffolded'
  | 'project:deleted'
  // PRD events (Product Requirements Documents)
  | 'prd:created'
  | 'prd:status:updated'
  // Discord monitoring events
  | 'discord:message:detected'
  // Linear monitoring events
  | 'linear:project:updated'
  | 'linear:issue:detected'
  // GitHub monitoring events
  | 'github:pr:detected'
  // Linear monitor events
  | 'linear-monitor:started'
  | 'linear-monitor:stopped'
  | 'linear-monitor:poll-requested'
  | 'linear-monitor:poll-error'
  | 'linear-monitor:project-detected'
  | 'linear-monitor:trigger-error'
  // Feature assignment events
  | 'feature-assignment:started'
  | 'feature-assignment:completed'
  | 'feature-assignment:failed'
  | 'feature-assignment:cancelled'
  | 'feature-assignment:em-agent-spawn'
  | 'feature-assignment:error'
  // Authority system events
  | 'authority:proposal-submitted'
  | 'authority:approved'
  | 'authority:rejected'
  | 'authority:awaiting-approval'
  | 'authority:agent-registered'
  | 'authority:trust-updated'
  | 'authority:idea-injected'
  | 'authority:pm-review-started'
  | 'authority:pm-review-approved'
  | 'authority:pm-review-changes-requested'
  | 'authority:cto-approved-idea'
  | 'authority:pm-research-started'
  | 'authority:pm-research-completed'
  | 'authority:pm-prd-ready'
  | 'authority:pm-epic-created'
  // Milestone lifecycle events
  | 'milestone:planning-started'
  | 'milestone:planned'
  | 'milestone:started'
  | 'milestone:completed'
  | 'milestone:cto-approval-requested'
  | 'milestone:cto-approved'
  // Project completion events
  | 'project:completed'
  // CoS intake events
  | 'cos:prd-submitted'
  // PR feedback loop events (EM dev lifecycle)
  | 'pr:feedback-received'
  | 'pr:changes-requested'
  | 'pr:approved'
  | 'feature:reassigned-for-fixes'
  | 'feature:worktree-cleaned'
  // Chief of Staff (CoS) events
  | 'cos:prd-submitted';

export type EventCallback = (type: EventType, payload: unknown) => void;
