/**
 * Event types for AutoMaker event system
 */

export type EventType =
  | 'agent:stream'
  | 'auto-mode:event'
  | 'auto-mode:started'
  | 'auto-mode:stopped'
  | 'auto-mode:idle'
  | 'auto-mode:error'
  | 'auto-mode:health-check'
  | 'backlog-plan:event'
  | 'feature:created'
  | 'feature:started'
  | 'feature:completed'
  | 'feature:stopped'
  | 'feature:error'
  | 'feature:progress'
  | 'feature:tool-use'
  | 'feature:follow-up-started'
  | 'feature:follow-up-completed'
  | 'feature:verified'
  | 'feature:committed'
  | 'feature:retry'
  | 'feature:recovery'
  | 'project:analysis-started'
  | 'project:analysis-progress'
  | 'project:analysis-completed'
  | 'project:analysis-error'
  | 'project:features:start'
  | 'project:features:progress'
  | 'project:features:error'
  | 'project:features:done'
  | 'suggestions:event'
  | 'spec-regeneration:event'
  | 'issue-validation:event'
  | 'ideation:stream'
  | 'ideation:session-started'
  | 'ideation:session-ended'
  | 'ideation:analysis'
  | 'ideation:analysis-started'
  | 'ideation:analysis-progress'
  | 'ideation:analysis-complete'
  | 'ideation:analysis-error'
  | 'ideation:suggestions'
  | 'ideation:idea-created'
  | 'ideation:idea-updated'
  | 'ideation:idea-deleted'
  | 'ideation:idea-converted'
  | 'worktree:init-started'
  | 'worktree:init-output'
  | 'worktree:init-completed'
  | 'dev-server:started'
  | 'dev-server:output'
  | 'dev-server:stopped'
  | 'skill:created'
  | 'memory:learning'
  | 'notification:created'
  | 'health:check-completed'
  | 'health:issue-detected'
  | 'health:issue-remediated'
  | 'scheduler:started'
  | 'scheduler:stopped'
  | 'scheduler:task_registered'
  | 'scheduler:task_unregistered'
  | 'scheduler:task_enabled'
  | 'scheduler:task_disabled'
  | 'scheduler:task_started'
  | 'scheduler:task_completed'
  | 'recovery_analysis'
  | 'recovery_started'
  | 'recovery_completed'
  | 'recovery_recorded'
  | 'recovery_escalated'
  // Ralph mode events (persistent retry loops)
  | 'ralph:started'
  | 'ralph:iteration_started'
  | 'ralph:iteration_completed'
  | 'ralph:verification_started'
  | 'ralph:verification_completed'
  | 'ralph:verified'
  | 'ralph:paused'
  | 'ralph:resumed'
  | 'ralph:stopped'
  | 'ralph:max_iterations'
  | 'ralph:error'
  | 'ralph:progress'
  // CodeRabbit review events
  | 'coderabbit:review-received'
  | 'coderabbit:feedback-processed'
  | 'coderabbit:link-created';

export type EventCallback = (type: EventType, payload: unknown) => void;
