/**
 * Shared Design System — Brand Tokens
 *
 * Tailwind v4 CSS preset extracted from the protoLabs marketing site (site/index.html).
 * Returns a CSS string ready to be inlined or written to a file and imported into any
 * Tailwind v4 project.
 *
 * Usage:
 *   import { getDesignTokensCss } from '@protolabsai/templates';
 *   // Write the CSS string to a file and @import it in your main CSS entry point.
 */

/**
 * Returns the complete Tailwind v4 CSS preset for the protoLabs brand design system.
 *
 * Includes:
 * - Surface color tokens (surface-0 through surface-3)
 * - Accent violet tokens (accent, accent-dim)
 * - Muted / semantic color tokens
 * - Geist font-family definitions
 * - Border opacity tokens
 * - Utility classes: .gradient-text, .glow, .input-glow
 * - Badge component classes: .badge, .badge-purple, .badge-green, .badge-yellow, .badge-blue, .badge-red
 * - Mockup panel classes: .mockup-panel, .mockup-bar, .mockup-dot, .mockup-body and semantic sub-classes
 * - Architecture diagram helpers: .arch-box, .arch-box-accent, .arch-arrow
 * - Animation utilities: .animate-fade-up, .animate-delay-{1-4}, .fade-section
 * - Cursor blink animation
 */
export function getDesignTokensCss(): string {
  return `/* =============================================================
 * protoLabs Brand Design System — Tailwind v4 CSS Preset
 * Generated by @protolabsai/templates · getDesignTokensCss()
 * ============================================================= */

/* ------------------------------------------------------------------
 * @theme — Tailwind v4 design tokens
 * These become available as Tailwind utility classes automatically
 * (e.g. bg-surface-0, text-accent, font-sans, etc.)
 * ------------------------------------------------------------------ */
@theme {
  /* Surface colors — dark zinc palette */
  --color-surface-0: #09090b;
  --color-surface-1: #111113;
  --color-surface-2: #18181b;
  --color-surface-3: #222225;

  /* Accent violet */
  --color-accent: #a78bfa;
  --color-accent-dim: #7c5cbf;

  /* Semantic / muted */
  --color-muted: #71717a;

  /* Semantic status colors */
  --color-success: #4ade80;
  --color-warning: #facc15;
  --color-info: #60a5fa;
  --color-danger: #f87171;

  /* Typography — Geist */
  --font-family-sans: 'Geist', system-ui, sans-serif;
  --font-family-mono: 'Geist Mono', monospace;

  /* Border opacity tokens */
  --border-subtle: rgba(255, 255, 255, 0.06);
  --border-faint: rgba(255, 255, 255, 0.04);
  --border-accent-muted: rgba(167, 139, 250, 0.3);

  /* Glow definitions */
  --glow-accent: 0 0 80px rgba(167, 139, 250, 0.08);
  --glow-input: 0 0 0 2px rgba(167, 139, 250, 0.3);
}

/* ------------------------------------------------------------------
 * Base resets that mirror the marketing site body defaults
 * ------------------------------------------------------------------ */
html {
  scroll-behavior: smooth;
}

body {
  background-color: var(--color-surface-0, #09090b);
  color: #fafafa;
  font-family: var(--font-family-sans, 'Geist', system-ui, sans-serif);
}

/* Focus-visible ring — consistent across interactive elements */
a:focus-visible,
button:focus-visible,
input:focus-visible {
  outline: 2px solid var(--color-accent, #a78bfa);
  outline-offset: 2px;
}

/* Skip-to-content link (accessibility) */
.skip-link {
  position: absolute;
  top: -100%;
  left: 16px;
  z-index: 100;
  padding: 8px 16px;
  background: var(--color-accent, #a78bfa);
  color: #fff;
  border-radius: 0 0 8px 8px;
  font-size: 14px;
  font-weight: 500;
  text-decoration: none;
  transition: top 0.2s;
}

.skip-link:focus {
  top: 0;
}

/* ------------------------------------------------------------------
 * Gradient text utility
 * ------------------------------------------------------------------ */
.gradient-text {
  background: linear-gradient(135deg, #a78bfa 0%, #818cf8 50%, #6366f1 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

/* ------------------------------------------------------------------
 * Glow utilities
 * ------------------------------------------------------------------ */
.glow {
  box-shadow: var(--glow-accent, 0 0 80px rgba(167, 139, 250, 0.08));
}

.input-glow:focus {
  box-shadow: var(--glow-input, 0 0 0 2px rgba(167, 139, 250, 0.3));
}

/* ------------------------------------------------------------------
 * Badge component
 * ------------------------------------------------------------------ */
.badge {
  display: inline-block;
  padding: 2px 8px;
  border-radius: 6px;
  font-size: 11px;
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.badge-purple {
  background: rgba(167, 139, 250, 0.15);
  color: var(--color-accent, #a78bfa);
}

.badge-green {
  background: rgba(74, 222, 128, 0.15);
  color: var(--color-success, #4ade80);
}

.badge-yellow {
  background: rgba(250, 204, 21, 0.15);
  color: var(--color-warning, #facc15);
}

.badge-blue {
  background: rgba(96, 165, 250, 0.15);
  color: var(--color-info, #60a5fa);
}

.badge-red {
  background: rgba(248, 113, 113, 0.15);
  color: var(--color-danger, #f87171);
}

/* ------------------------------------------------------------------
 * Mockup panel — terminal / code mock components
 * ------------------------------------------------------------------ */
.mockup-panel {
  background: var(--color-surface-1, #111113);
  border: 1px solid var(--border-subtle, rgba(255, 255, 255, 0.06));
  border-radius: 12px;
  overflow: hidden;
  font-family: var(--font-family-mono, 'Geist Mono', monospace);
  font-size: 13px;
  line-height: 1.6;
}

.mockup-bar {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 10px 14px;
  background: rgba(255, 255, 255, 0.03);
  border-bottom: 1px solid var(--border-subtle, rgba(255, 255, 255, 0.06));
}

.mockup-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
}

.mockup-body {
  padding: 16px;
  color: #a1a1aa;
}

.mockup-body .prompt {
  color: var(--color-accent, #a78bfa);
}

.mockup-body .cmd {
  color: #e4e4e7;
}

.mockup-body .success {
  color: var(--color-success, #4ade80);
}

.mockup-body .warn {
  color: var(--color-warning, #facc15);
}

.mockup-body .dim {
  color: #52525b;
}

.mockup-body .info {
  color: var(--color-info, #60a5fa);
}

.mockup-sep {
  border-top: 1px solid var(--border-faint, rgba(255, 255, 255, 0.04));
  margin: 8px 0;
}

/* ------------------------------------------------------------------
 * Cursor blink animation (terminal UX)
 * ------------------------------------------------------------------ */
@keyframes blink {
  0%,
  100% {
    opacity: 1;
  }
  50% {
    opacity: 0;
  }
}

.cursor {
  display: inline-block;
  width: 8px;
  height: 16px;
  background: var(--color-accent, #a78bfa);
  vertical-align: text-bottom;
  animation: blink 1.2s step-end infinite;
}

/* ------------------------------------------------------------------
 * Architecture diagram helpers
 * ------------------------------------------------------------------ */
.arch-box {
  background: var(--color-surface-2, #18181b);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 8px;
  padding: 10px 16px;
  font-size: 13px;
  font-family: var(--font-family-mono, 'Geist Mono', monospace);
  color: #e4e4e7;
  text-align: center;
  white-space: nowrap;
}

.arch-box-accent {
  border-color: var(--border-accent-muted, rgba(167, 139, 250, 0.3));
  background: rgba(167, 139, 250, 0.08);
}

.arch-arrow {
  color: var(--color-accent, #a78bfa);
  font-size: 18px;
  line-height: 1;
}

/* ------------------------------------------------------------------
 * Check icon badge
 * ------------------------------------------------------------------ */
.check-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: rgba(74, 222, 128, 0.2);
  color: var(--color-success, #4ade80);
  font-size: 10px;
  flex-shrink: 0;
}

/* ------------------------------------------------------------------
 * Score bar
 * ------------------------------------------------------------------ */
.score-bar {
  height: 4px;
  border-radius: 2px;
  background: var(--color-surface-3, #222225);
}

.score-fill {
  height: 100%;
  border-radius: 2px;
}

/* ------------------------------------------------------------------
 * Dependency line (vertical connector)
 * ------------------------------------------------------------------ */
.dep-line {
  width: 2px;
  background: var(--border-accent-muted, rgba(167, 139, 250, 0.3));
}

/* ------------------------------------------------------------------
 * Scroll-triggered fade-in animation
 * ------------------------------------------------------------------ */
.fade-section {
  opacity: 0;
  transform: translateY(24px);
  transition:
    opacity 0.7s ease-out,
    transform 0.7s ease-out;
}

.fade-section.visible {
  opacity: 1;
  transform: translateY(0);
}

/* ------------------------------------------------------------------
 * Hero entrance animations
 * ------------------------------------------------------------------ */
@keyframes fade-up {
  from {
    opacity: 0;
    transform: translateY(24px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.animate-fade-up {
  animation: fade-up 0.8s ease-out forwards;
}

.animate-delay-1 {
  animation-delay: 0.15s;
  opacity: 0;
}

.animate-delay-2 {
  animation-delay: 0.3s;
  opacity: 0;
}

.animate-delay-3 {
  animation-delay: 0.45s;
  opacity: 0;
}

.animate-delay-4 {
  animation-delay: 0.6s;
  opacity: 0;
}
`;
}

/**
 * Returns only the Tailwind v4 @theme block with CSS custom property tokens.
 * Useful when you need to merge tokens into an existing CSS file rather than
 * importing the full preset.
 */
export function getDesignTokensThemeBlock(): string {
  return `@theme {
  /* Surface colors */
  --color-surface-0: #09090b;
  --color-surface-1: #111113;
  --color-surface-2: #18181b;
  --color-surface-3: #222225;

  /* Accent violet */
  --color-accent: #a78bfa;
  --color-accent-dim: #7c5cbf;

  /* Semantic / muted */
  --color-muted: #71717a;

  /* Semantic status colors */
  --color-success: #4ade80;
  --color-warning: #facc15;
  --color-info: #60a5fa;
  --color-danger: #f87171;

  /* Typography */
  --font-family-sans: 'Geist', system-ui, sans-serif;
  --font-family-mono: 'Geist Mono', monospace;

  /* Border opacity tokens */
  --border-subtle: rgba(255, 255, 255, 0.06);
  --border-faint: rgba(255, 255, 255, 0.04);
  --border-accent-muted: rgba(167, 139, 250, 0.3);

  /* Glow definitions */
  --glow-accent: 0 0 80px rgba(167, 139, 250, 0.08);
  --glow-input: 0 0 0 2px rgba(167, 139, 250, 0.3);
}
`;
}

/**
 * Typed record of raw token values for use in JS/TS contexts (e.g. inline styles,
 * canvas rendering, theme interpolation) where CSS variables are unavailable.
 */
export const designTokens = {
  colors: {
    surface: {
      0: '#09090b',
      1: '#111113',
      2: '#18181b',
      3: '#222225',
    },
    accent: {
      DEFAULT: '#a78bfa',
      dim: '#7c5cbf',
    },
    muted: '#71717a',
    success: '#4ade80',
    warning: '#facc15',
    info: '#60a5fa',
    danger: '#f87171',
  },
  fonts: {
    sans: "'Geist', system-ui, sans-serif",
    mono: "'Geist Mono', monospace",
  },
  borders: {
    subtle: 'rgba(255, 255, 255, 0.06)',
    faint: 'rgba(255, 255, 255, 0.04)',
    accentMuted: 'rgba(167, 139, 250, 0.3)',
  },
  gradients: {
    text: 'linear-gradient(135deg, #a78bfa 0%, #818cf8 50%, #6366f1 100%)',
  },
  glows: {
    accent: '0 0 80px rgba(167, 139, 250, 0.08)',
    input: '0 0 0 2px rgba(167, 139, 250, 0.3)',
  },
} as const;

export type DesignTokens = typeof designTokens;
