/**
 * PRD Review Modal - Review and approve/reject PRDs generated by PM Agent
 *
 * Displayed when a feature reaches 'prd_ready' state.
 * User can approve (triggers ProjM decomposition) or reject (removes from workflow).
 */

import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@protolabs/ui/atoms';
import { Button } from '@protolabs/ui/atoms';
import { Markdown } from '@protolabs/ui/molecules';
import { Spinner } from '@protolabs/ui/atoms';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@protolabs/ui/atoms';
import { ChevronDown, CheckCircle, XCircle } from 'lucide-react';
import { toast } from 'sonner';
import type { Feature } from '@automaker/types';

interface PRDReviewModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  feature: Feature | null;
  projectPath: string;
  onApprove: () => Promise<void>;
  onReject: () => Promise<void>;
}

export function PRDReviewModal({
  open,
  onOpenChange,
  feature,
  projectPath,
  onApprove,
  onReject,
}: PRDReviewModalProps) {
  const [isApproving, setIsApproving] = useState(false);
  const [isRejecting, setIsRejecting] = useState(false);
  const [showOriginalSuggestion, setShowOriginalSuggestion] = useState(false);

  if (!feature) return null;

  const handleApprove = async () => {
    setIsApproving(true);
    try {
      await onApprove();
      toast.success('PRD approved - breaking down into epics...');
      onOpenChange(false);
    } catch (error) {
      console.error('Approve PRD error:', error);
      toast.error('Failed to approve PRD');
    } finally {
      setIsApproving(false);
    }
  };

  const handleReject = async () => {
    setIsRejecting(true);
    try {
      await onReject();
      toast.info('PRD rejected');
      onOpenChange(false);
    } catch (error) {
      console.error('Reject PRD error:', error);
      toast.error('Failed to reject PRD');
    } finally {
      setIsRejecting(false);
    }
  };

  const originalSuggestion = feature.prdMetadata?.originalSuggestion;
  const isLoading = isApproving || isRejecting;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle>Review PRD: {feature.title}</DialogTitle>
          <DialogDescription>
            Generated by PM Agent from ideation suggestion. Review and approve to begin
            implementation.
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto space-y-4 py-4">
          {/* PRD Content */}
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <Markdown>{feature.description || ''}</Markdown>
          </div>

          {/* Original Suggestion (collapsible) */}
          {originalSuggestion && (
            <Collapsible
              open={showOriginalSuggestion}
              onOpenChange={setShowOriginalSuggestion}
              className="border rounded-lg p-4 bg-muted/30"
            >
              <CollapsibleTrigger className="flex items-center justify-between w-full text-sm font-medium">
                <span>Original Suggestion</span>
                <ChevronDown
                  className={`w-4 h-4 transition-transform ${showOriginalSuggestion ? 'rotate-180' : ''}`}
                />
              </CollapsibleTrigger>
              <CollapsibleContent className="mt-3 space-y-2 text-sm">
                <div>
                  <strong>Title:</strong> {originalSuggestion.title}
                </div>
                <div>
                  <strong>Description:</strong> {originalSuggestion.description}
                </div>
                {originalSuggestion.rationale && (
                  <div>
                    <strong>Rationale:</strong> {originalSuggestion.rationale}
                  </div>
                )}
                {originalSuggestion.relatedFiles && originalSuggestion.relatedFiles.length > 0 && (
                  <div>
                    <strong>Related Files:</strong>
                    <ul className="list-disc pl-5 mt-1">
                      {originalSuggestion.relatedFiles.map((file, idx) => (
                        <li key={idx}>{file}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </CollapsibleContent>
            </Collapsible>
          )}
        </div>

        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isLoading}>
            Close
          </Button>
          <Button
            variant="destructive"
            onClick={handleReject}
            disabled={isLoading}
            className="gap-2"
          >
            {isRejecting ? (
              <>
                <Spinner size="sm" />
                Rejecting...
              </>
            ) : (
              <>
                <XCircle className="w-4 h-4" />
                Reject
              </>
            )}
          </Button>
          <Button onClick={handleApprove} disabled={isLoading} className="gap-2">
            {isApproving ? (
              <>
                <Spinner size="sm" />
                Approving...
              </>
            ) : (
              <>
                <CheckCircle className="w-4 h-4" />
                Approve
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
