#!/bin/bash
# Automaker Staging Setup Script
# One-command setup for a staging environment with high-concurrency agent execution.
#
# Usage:
#   ./scripts/setup-staging.sh              # Full setup (build + start)
#   ./scripts/setup-staging.sh --build      # Rebuild images only
#   ./scripts/setup-staging.sh --start      # Start without rebuilding
#   ./scripts/setup-staging.sh --drain      # Gracefully stop agents before deploy
#   ./scripts/setup-staging.sh --stop       # Stop services
#   ./scripts/setup-staging.sh --status     # Show status
#   ./scripts/setup-staging.sh --teardown   # Stop and remove volumes
#
# Uses .env for API keys. Creates one if missing.
# See docs/infra/staging-deployment.md for full documentation.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$PROJECT_ROOT/docker-compose.staging.yml"
ENV_FILE="$PROJECT_ROOT/.env"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()   { echo -e "${RED}[ERROR]${NC} $1"; }

# ─── Prerequisites ───────────────────────────────────────────────────────────

check_prereqs() {
  info "Checking prerequisites..."

  if ! command -v docker &>/dev/null; then
    err "Docker is not installed. Install with: curl -fsSL https://get.docker.com | sh"
    exit 1
  fi
  ok "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')"

  if ! docker compose version &>/dev/null; then
    err "Docker Compose plugin not found. Install with: sudo apt install docker-compose-plugin"
    exit 1
  fi
  ok "Docker Compose $(docker compose version --short)"

  if ! docker info &>/dev/null 2>&1; then
    err "Docker daemon is not running. Start with: sudo systemctl start docker"
    exit 1
  fi
  ok "Docker daemon running"

  if [ ! -f "$COMPOSE_FILE" ]; then
    err "docker-compose.staging.yml not found at $COMPOSE_FILE"
    exit 1
  fi
  ok "Compose file found"
}

# ─── Environment ─────────────────────────────────────────────────────────────

setup_env() {
  if [ -f "$ENV_FILE" ]; then
    info "Using existing $ENV_FILE"

    # Auto-detect resource limits if not already in .env
    if ! grep -q 'MEMORY_LIMIT' "$ENV_FILE" 2>/dev/null; then
      info "Adding resource limits to .env..."
      append_resource_config
    fi
    return
  fi

  info "Creating $ENV_FILE..."

  local uid=$(id -u)
  local gid=$(id -g)

  cat > "$ENV_FILE" <<EOF
# Automaker Environment
# Generated by setup-staging.sh on $(date -Iseconds)

# ── API Keys ─────────────────────────────────────────────────────────────────
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
AUTOMAKER_API_KEY=${AUTOMAKER_API_KEY:-automaker-staging-$(openssl rand -hex 8)}
GH_TOKEN=${GH_TOKEN:-}
CLAUDE_OAUTH_CREDENTIALS=${CLAUDE_OAUTH_CREDENTIALS:-}
CURSOR_AUTH_TOKEN=${CURSOR_AUTH_TOKEN:-}

# ── Container User ───────────────────────────────────────────────────────────
UID=$uid
GID=$gid

# ── Paths ────────────────────────────────────────────────────────────────────
PROJECTS_MOUNT=/home/$(whoami)/dev
ALLOWED_ROOT_DIRECTORY=/home/$(whoami)/dev
EOF

  append_resource_config
  ok "Created $ENV_FILE"
}

append_resource_config() {
  local total_ram_gb
  total_ram_gb=$(free -g | awk '/Mem:/ {print $2}')
  local memory_limit
  if [ "$total_ram_gb" -ge 96 ]; then
    memory_limit="64G"
  elif [ "$total_ram_gb" -ge 48 ]; then
    memory_limit="48G"
  elif [ "$total_ram_gb" -ge 24 ]; then
    memory_limit="16G"
  else
    memory_limit="8G"
  fi

  local cpu_count
  cpu_count=$(nproc)
  local cpu_limit
  if [ "$cpu_count" -ge 16 ]; then
    cpu_limit=12
  elif [ "$cpu_count" -ge 8 ]; then
    cpu_limit=8
  else
    cpu_limit=$((cpu_count - 1))
  fi

  # Auto-detect concurrency based on RAM
  local max_concurrency
  if [ "$total_ram_gb" -ge 96 ]; then
    max_concurrency=8
  elif [ "$total_ram_gb" -ge 48 ]; then
    max_concurrency=6
  elif [ "$total_ram_gb" -ge 24 ]; then
    max_concurrency=4
  else
    max_concurrency=2
  fi

  cat >> "$ENV_FILE" <<EOF

# ── Resources (auto-detected: ${total_ram_gb}GB RAM, ${cpu_count} CPUs) ─────
MEMORY_LIMIT=$memory_limit
CPU_LIMIT=$cpu_limit
NODE_MAX_OLD_SPACE=32768
AUTOMAKER_MAX_CONCURRENCY=$max_concurrency
LOG_LEVEL=info
EOF

  ok "Resource config: ${memory_limit} RAM, ${cpu_limit} CPUs"
}

# ─── Build ───────────────────────────────────────────────────────────────────

build_images() {
  info "Building images..."
  cd "$PROJECT_ROOT"

  if [ ! -f "$ENV_FILE" ]; then
    err "Missing $ENV_FILE — cannot build"
    exit 1
  fi

  # Build critical services first, storybook separately.
  # If storybook fails to build, the deploy continues without it.
  info "Building critical images (server, ui, docs)..."
  docker compose -f "$COMPOSE_FILE" build server ui docs
  ok "Critical images built"

  info "Building storybook image..."
  if docker compose -f "$COMPOSE_FILE" build storybook; then
    ok "Storybook image built"
  else
    warn "Storybook build failed — deploy will continue without it"
  fi
}

# ─── Stop existing ───────────────────────────────────────────────────────────

stop_existing() {
  info "Stopping existing Automaker containers..."

  # Use the staging compose file to cleanly stop and remove containers + networks.
  # This is the only compose file used in staging — never mix with docker-compose.yml.
  docker compose -f "$COMPOSE_FILE" down 2>/dev/null || true

  # Force-remove if compose down didn't clean up (e.g. containers from a different project)
  for name in automaker-server automaker-ui automaker-docs automaker-storybook; do
    if docker ps -aq --filter "name=^${name}$" | grep -q .; then
      docker rm -f "$name" 2>/dev/null || true
    fi
  done

  ok "Existing containers stopped"
}

# ─── Start ───────────────────────────────────────────────────────────────────

start_services() {
  info "Starting services..."
  cd "$PROJECT_ROOT"

  stop_existing

  # Ensure named volumes exist (external: true in compose won't auto-create them)
  for vol in automaker-data automaker-claude-config automaker-cursor-config \
             automaker-opencode-data automaker-opencode-config automaker-opencode-cache; do
    docker volume create "$vol" >/dev/null
  done

  # Start critical services first
  docker compose -f "$COMPOSE_FILE" up -d server ui docs

  # Start storybook separately — failure is non-fatal
  docker compose -f "$COMPOSE_FILE" up -d storybook 2>/dev/null || warn "Storybook failed to start (image may not exist)"

  info "Waiting for health check..."
  local retries=0
  local max_retries=30

  while [ $retries -lt $max_retries ]; do
    if curl -sf http://localhost:${API_PORT:-3008}/api/health &>/dev/null; then
      ok "Server is healthy"
      break
    fi
    retries=$((retries + 1))
    sleep 2
  done

  if [ $retries -eq $max_retries ]; then
    warn "Health check timed out after 60s. Check logs:"
    echo "  docker compose -f $COMPOSE_FILE logs server"
  fi

  show_status
}

# ─── Stop ────────────────────────────────────────────────────────────────────

stop_services() {
  info "Stopping services..."
  cd "$PROJECT_ROOT"
  docker compose -f "$COMPOSE_FILE" down
  ok "Services stopped"
}

# ─── Teardown ────────────────────────────────────────────────────────────────

teardown() {
  warn "This will stop services and DELETE all volumes (data, configs)."
  read -p "Are you sure? (y/N) " confirm
  if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
    info "Cancelled."
    exit 0
  fi

  cd "$PROJECT_ROOT"
  docker compose -f "$COMPOSE_FILE" down -v

  # External volumes are not removed by compose down -v, so remove them explicitly
  for vol in automaker-data automaker-claude-config automaker-cursor-config \
             automaker-opencode-data automaker-opencode-config automaker-opencode-cache; do
    docker volume rm "$vol" >/dev/null 2>&1 || true
  done

  ok "Services stopped and volumes removed"
}

# ─── Status ──────────────────────────────────────────────────────────────────

show_status() {
  echo ""
  echo -e "${BLUE}═══ Automaker Staging Status ═══${NC}"
  echo ""

  cd "$PROJECT_ROOT"

  # Container status
  local ps_output
  ps_output=$(docker compose -f "$COMPOSE_FILE" ps 2>/dev/null) || true
  if echo "$ps_output" | grep -q automaker; then
    echo "$ps_output"
  else
    warn "No containers running"
    return
  fi

  echo ""

  # Resource usage
  docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}" 2>/dev/null | grep -E "NAME|automaker" || true

  echo ""

  # Endpoints
  local api_port="${API_PORT:-3008}"
  local ui_port="${UI_PORT:-3007}"
  local docs_port="${DOCS_PORT:-3009}"
  echo -e "  UI:     ${GREEN}http://localhost:${ui_port}${NC}"
  echo -e "  API:    ${GREEN}http://localhost:${api_port}${NC}"
  echo -e "  Docs:   ${GREEN}http://localhost:${docs_port}${NC}"
  local storybook_port="${STORYBOOK_PORT:-6666}"
  echo -e "  Storybook: ${GREEN}http://localhost:${storybook_port}${NC}"
  echo -e "  Health: ${GREEN}http://localhost:${api_port}/api/health${NC}"
  echo ""
}

# ─── Drain ────────────────────────────────────────────────────────────────────

drain_agents() {
  info "Draining running agents before deploy..."

  local api_port="${API_PORT:-3008}"
  local api_key="${AUTOMAKER_API_KEY:-}"

  if [ -z "$api_key" ]; then
    warn "AUTOMAKER_API_KEY not set, skipping drain"
    return 0
  fi

  local response
  response=$(curl -sf -X POST "http://localhost:${api_port}/api/deploy/drain" \
    -H "Content-Type: application/json" \
    -H "X-API-Key: ${api_key}" \
    --max-time 180 2>&1) || {
    warn "Drain failed or server not running — continuing with deploy"
    return 0
  }

  ok "Drain complete: $response"
}

# ─── Main ────────────────────────────────────────────────────────────────────

# Source env file if it exists (for port vars)
# Temporarily disable nounset (-u) because .env may reference unset vars
# (e.g., AUTOMAKER_API_KEY=${AUTOMAKER_API_KEY} passthrough pattern)
if [ -f "$ENV_FILE" ]; then
  set +u
  set -a
  source "$ENV_FILE" 2>/dev/null || true
  set +a
  set -u
fi

case "${1:-}" in
  --build)
    check_prereqs
    setup_env
    build_images
    ;;
  --start)
    check_prereqs
    start_services
    ;;
  --drain)
    drain_agents
    ;;
  --stop)
    stop_services
    ;;
  --status)
    show_status
    ;;
  --teardown)
    teardown
    ;;
  --help|-h)
    echo "Usage: $0 [--build|--start|--drain|--stop|--status|--teardown|--help]"
    echo ""
    echo "  (no args)   Full setup: check prereqs, build images, start services"
    echo "  --build     Rebuild images only"
    echo "  --start     Start without rebuilding"
    echo "  --drain     Gracefully stop agents before deploy"
    echo "  --stop      Stop services"
    echo "  --status    Show status"
    echo "  --teardown  Stop and remove all volumes"
    echo "  --help      Show this help"
    ;;
  *)
    # Full setup
    check_prereqs
    setup_env
    build_images
    start_services
    ;;
esac
