/**
 * Draft Summary Node
 *
 * Generates a compelling milestone summary from achievements and lessons.
 * Currently uses deterministic template — will be LLM-powered
 * when integrated into the server runtime.
 *
 * The LLM node will:
 * - Craft engaging narrative from achievements
 * - Integrate lessons learned naturally
 * - Preview next milestone context
 * - Generate actionable insights
 */

import type { MilestoneSummaryState } from '../types.js';

/**
 * Deterministic summary draft (mock)
 *
 * In production, this will be replaced with an LLM call that generates
 * a compelling, human-readable milestone summary.
 */
export async function draftSummary(
  state: MilestoneSummaryState
): Promise<Partial<MilestoneSummaryState>> {
  try {
    const { milestoneName, achievements, lessonsLearned, revisionCount, reviewFeedback } = state;

    // If we have review feedback, incorporate it into the revision
    const revisionNote =
      revisionCount > 0 && reviewFeedback
        ? `\n\n<!-- Revision ${revisionCount}: ${reviewFeedback} -->\n`
        : '';

    // Mock template-based summary
    const summary = `# Milestone Complete: ${milestoneName}

${revisionNote}
## Overview

We've successfully completed the **${milestoneName}** milestone, delivering ${achievements.length} feature${achievements.length !== 1 ? 's' : ''} that ${achievements.length > 1 ? 'advance' : 'advances'} our project capabilities.

## Key Achievements

${achievements
  .map(
    (a) =>
      `- **${a.title}** (PR #${a.prNumber ?? 'N/A'}): ${a.description}
  - Cost: $${a.costUsd?.toFixed(2) ?? '0.00'}, Lines: +${a.linesChanged?.added ?? 0}/-${a.linesChanged?.deleted ?? 0}`
  )
  .join('\n')}

## Lessons Learned

${lessonsLearned
  .map(
    (lesson) => `### ${lesson.category.charAt(0).toUpperCase() + lesson.category.slice(1)}
- **Insight**: ${lesson.insight}
- **Impact**: ${lesson.impact}${lesson.actionItems && lesson.actionItems.length > 0 ? `\n- **Actions**: ${lesson.actionItems.join(', ')}` : ''}`
  )
  .join('\n\n')}

## Next Steps

With this milestone complete, we're ready to move forward to the next phase of development. The foundation we've built here will support upcoming features and enhancements.

---
*Generated by Automaker Milestone Summary Flow*
`;

    return { draftSummary: summary };
  } catch (err) {
    return {
      error: `Failed to draft summary: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}
